import { ITrRequest } from 'src/types';



export const INIT_REQUEST_VALUE: ITrRequest = {
  id: 7,
  entities_id: null,
  application_id: 1,
  category: 1,
  ticket_name: '',
  creation_date: '',
  closed_date: null,
  creator: '',
  status: '',
  urgency: '',
  expected_completion_date: '',
  type: '',
  department_code: '',
  department_name: '',
  is_project: null,
  background: '',
  issue_description: '',
  business_impact: '',
  created_at: '',
  created_by: '',
  impact: null,
  priority: null,
  background_what: '',
  background_who: '',
  background_when: '',
  background_where: '',
  background_why: '',
  background_how: '',
  mst_category: {
    id: 1,
    category_code: '',
    category_name: '',
    is_active: '',
    created_at: null,
    created_by: null,
  },
  mst_application: {
    id: 1,
    application_name: '',
    group_id_technician: '',
    entity_id: 2,
    department_code: '',
    is_deleted: false,
    created_at: '',
    created_by: null,
  },
};

export const SELF_SERVICE_PROFILE = {
  id: 14,
  employee_code: '',
  profile_id: 3,
  entities_id: 1,
  created_at: null,
  created_by: null,
  mst_profile: {
    id: 3,
    profile_name: 'Self-Services',
    is_deleted: false,
    created_at: null,
    created_by: null,
  },
};
